[tasks."test:behavior"]
description = "Run behavioral tests (usage: mise run test:behavior [Features/Smoke/Smoke.feature])"
usage = '''
arg "[testparams]" var=#true
'''
run = 'docker compose -f ../../../docker-compose.yml exec -e FLOW_CONTEXT=Testing/Behat neos bash -c "cd /app && FLOW_CONTEXT=Testing/Behat ./flow doctrine:migrate && bin/behat -c Packages/Plugins/Sandstorm.NodeTypes.Folder/Tests/Behavior/behat.yml.dist ${usage_testparams}"'
