Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          "Sandstorm.NodeTypes.Folder":
            - "NodeTypes/*/*"
    fusion:
      autoInclude:
        Sandstorm.NodeTypes.Folder: true
  ContentRepositoryRegistry:
    presets:
      "default":
        projections:
          "Neos.Neos:DocumentUriPathProjection":
            factoryObjectName: Sandstorm\NodeTypes\Folder\FrontendRouting\Projection\DocumentUriPathProjectionFactory
